version: '3.8'

services:
  testManagerPostgres:
    image: postgres:latest
    ports:
      - "5437:5437"
    env_file:
      - .env
    volumes:
      - test_manager_data:/var/lib/postgresql/data

  testManager:
    image: testmanager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      - testManagerPostgres


volumes:
    test_manager_data:
    blob:
        external: false